import type { Pool } from "./client.js";

/**
 * Postgres + pgvector port of src/db/schema.sql.
 *
 * Mapping notes:
 * - INTEGER PRIMARY KEY -> INTEGER GENERATED BY DEFAULT AS IDENTITY (explicit
 *   ids stay insertable so JSONL exchange preserves ids across backends).
 * - strftime('%Y-%m-%dT%H:%M:%fZ','now') defaults -> timestamptz DEFAULT now()
 *   (read back through a type parser that emits the identical ISO string).
 * - REAL -> DOUBLE PRECISION (no float32 rounding of confidence/importance).
 * - FTS5 virtual tables + sync triggers -> stored generated tsvector columns
 *   with GIN indexes. Only the columns that were actually indexed in FTS5 are
 *   included (e.g. semantic_memories.scope and episodes.session were
 *   UNINDEXED and stay out of the vector).
 * - local-hash embeddings gain a vector(64) column with HNSW indexes; other
 *   providers keep vector_json only and use exact KNN (documented in README).
 */
export const PG_SCHEMA_SQL = `
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS entities (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project     TEXT NOT NULL,
  name        TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  search_vector TSVECTOR GENERATED ALWAYS AS
    (to_tsvector('english', name || ' ' || entity_type)) STORED,
  UNIQUE(project, name)
);

CREATE TABLE IF NOT EXISTS observations (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_id  INTEGER NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
  content    TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(entity_id, content)
);

CREATE TABLE IF NOT EXISTS relations (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project        TEXT NOT NULL,
  from_entity_id INTEGER NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
  to_entity_id   INTEGER NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
  relation_type  TEXT NOT NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(project, from_entity_id, to_entity_id, relation_type)
);

CREATE TABLE IF NOT EXISTS memory_items (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project    TEXT NOT NULL,
  kind       TEXT NOT NULL,
  title      TEXT,
  content    TEXT NOT NULL,
  tags_json  TEXT,
  source     TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  search_vector TSVECTOR GENERATED ALWAYS AS
    (to_tsvector('english', kind || ' ' || COALESCE(title, '') || ' ' || content)) STORED
);

CREATE TABLE IF NOT EXISTS episodes (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project       TEXT NOT NULL,
  session       TEXT,
  actor         TEXT,
  role          TEXT NOT NULL DEFAULT 'user',
  content       TEXT NOT NULL,
  source        TEXT,
  metadata_json TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  search_vector TSVECTOR GENERATED ALWAYS AS
    (to_tsvector('english',
      COALESCE(actor, '') || ' ' || role || ' ' || content || ' ' || COALESCE(source, ''))
    ) STORED
);

CREATE TABLE IF NOT EXISTS semantic_memories (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project           TEXT NOT NULL,
  scope             TEXT NOT NULL DEFAULT 'project',
  kind              TEXT NOT NULL DEFAULT 'fact',
  subject           TEXT NOT NULL,
  predicate         TEXT NOT NULL DEFAULT 'states',
  object            TEXT,
  content           TEXT NOT NULL,
  confidence        DOUBLE PRECISION NOT NULL DEFAULT 0.65,
  importance        DOUBLE PRECISION NOT NULL DEFAULT 0.5,
  status            TEXT NOT NULL DEFAULT 'active'
                    CHECK (status IN ('active', 'superseded', 'invalidated')),
  valid_from        TIMESTAMPTZ,
  valid_to          TIMESTAMPTZ,
  last_confirmed_at TIMESTAMPTZ,
  supersedes_id     INTEGER REFERENCES semantic_memories(id) ON DELETE SET NULL,
  metadata_json     TEXT,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  search_vector TSVECTOR GENERATED ALWAYS AS
    (to_tsvector('english',
      kind || ' ' || subject || ' ' || predicate || ' ' ||
      COALESCE(object, '') || ' ' || content)
    ) STORED
);

CREATE TABLE IF NOT EXISTS memory_lifecycle (
  memory_id   INTEGER PRIMARY KEY REFERENCES semantic_memories(id) ON DELETE CASCADE,
  status      TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'archived')),
  reason      TEXT,
  archived_at TIMESTAMPTZ,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS memory_sources (
  memory_id  INTEGER NOT NULL REFERENCES semantic_memories(id) ON DELETE CASCADE,
  episode_id INTEGER NOT NULL REFERENCES episodes(id) ON DELETE CASCADE,
  quote      TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (memory_id, episode_id)
);

CREATE TABLE IF NOT EXISTS memory_conflicts (
  id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project            TEXT NOT NULL,
  memory_id          INTEGER NOT NULL REFERENCES semantic_memories(id) ON DELETE CASCADE,
  conflicting_id     INTEGER NOT NULL REFERENCES semantic_memories(id) ON DELETE CASCADE,
  reason             TEXT NOT NULL,
  resolution_status  TEXT NOT NULL DEFAULT 'open'
                     CHECK (resolution_status IN ('open', 'resolved', 'ignored')),
  resolved_memory_id INTEGER REFERENCES semantic_memories(id) ON DELETE SET NULL,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  resolved_at        TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS entity_aliases (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project        TEXT NOT NULL,
  canonical_name TEXT NOT NULL,
  alias          TEXT NOT NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(project, alias)
);

CREATE TABLE IF NOT EXISTS claim_versions (
  id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  memory_id             INTEGER NOT NULL REFERENCES semantic_memories(id) ON DELETE CASCADE,
  project               TEXT NOT NULL,
  scope                 TEXT NOT NULL,
  kind                  TEXT NOT NULL,
  subject               TEXT NOT NULL,
  predicate             TEXT NOT NULL,
  object                TEXT,
  content               TEXT NOT NULL,
  confidence            DOUBLE PRECISION NOT NULL,
  importance            DOUBLE PRECISION NOT NULL,
  status                TEXT NOT NULL CHECK (status IN ('active', 'superseded', 'invalidated')),
  valid_from            TIMESTAMPTZ,
  valid_to              TIMESTAMPTZ,
  recorded_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  retracted_at          TIMESTAMPTZ,
  supersedes_version_id INTEGER REFERENCES claim_versions(id) ON DELETE SET NULL,
  metadata_json         TEXT,
  extractor_id          TEXT NOT NULL DEFAULT 'manual',
  extractor_version     TEXT NOT NULL DEFAULT '1',
  search_vector TSVECTOR GENERATED ALWAYS AS
    (to_tsvector('english',
      kind || ' ' || subject || ' ' || predicate || ' ' ||
      COALESCE(object, '') || ' ' || content)
    ) STORED
);

CREATE TABLE IF NOT EXISTS memory_embeddings (
  memory_id    INTEGER PRIMARY KEY REFERENCES semantic_memories(id) ON DELETE CASCADE,
  project      TEXT NOT NULL,
  provider     TEXT NOT NULL DEFAULT 'local-hash',
  dimension    INTEGER NOT NULL,
  vector_json  TEXT NOT NULL,
  embedding    vector(64),
  content_hash TEXT NOT NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS episode_embeddings (
  episode_id   INTEGER PRIMARY KEY REFERENCES episodes(id) ON DELETE CASCADE,
  project      TEXT NOT NULL,
  provider     TEXT NOT NULL DEFAULT 'local-hash',
  dimension    INTEGER NOT NULL,
  vector_json  TEXT NOT NULL,
  embedding    vector(64),
  content_hash TEXT NOT NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS claim_version_embeddings (
  claim_version_id INTEGER PRIMARY KEY REFERENCES claim_versions(id) ON DELETE CASCADE,
  project      TEXT NOT NULL,
  provider     TEXT NOT NULL DEFAULT 'local-hash',
  dimension    INTEGER NOT NULL,
  vector_json  TEXT NOT NULL,
  embedding    vector(64),
  content_hash TEXT NOT NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS memory_evidence (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  claim_version_id  INTEGER NOT NULL REFERENCES claim_versions(id) ON DELETE CASCADE,
  episode_id        INTEGER NOT NULL REFERENCES episodes(id) ON DELETE CASCADE,
  quote             TEXT NOT NULL,
  span_start        INTEGER,
  span_end          INTEGER,
  content_hash      TEXT NOT NULL,
  polarity          TEXT NOT NULL DEFAULT 'supports'
                    CHECK (polarity IN ('supports', 'contradicts', 'mentions')),
  actor             TEXT,
  source            TEXT,
  observed_at       TEXT,
  ingested_at       TEXT NOT NULL,
  extractor_id      TEXT NOT NULL,
  extractor_version TEXT NOT NULL,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(claim_version_id, episode_id, span_start, span_end, polarity)
);

CREATE TABLE IF NOT EXISTS conflict_resolution_events (
  id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conflict_id        INTEGER NOT NULL REFERENCES memory_conflicts(id) ON DELETE CASCADE,
  project            TEXT NOT NULL,
  action             TEXT NOT NULL CHECK (action IN ('resolved', 'ignored')),
  resolved_memory_id INTEGER REFERENCES semantic_memories(id) ON DELETE SET NULL,
  actor              TEXT,
  reason             TEXT,
  metadata_json      TEXT,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS memory_access_log (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project     TEXT NOT NULL,
  query       TEXT NOT NULL,
  intent      TEXT NOT NULL,
  result_json TEXT NOT NULL,
  latency_ms  INTEGER NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS benchmark_runs (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project      TEXT NOT NULL,
  name         TEXT NOT NULL,
  metrics_json TEXT NOT NULL,
  report       TEXT NOT NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS schema_migrations (
  version    INTEGER PRIMARY KEY,
  name       TEXT NOT NULL,
  applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS wiki_projection_state (
  project      TEXT NOT NULL,
  path         TEXT NOT NULL,
  revision     TEXT NOT NULL,
  content_hash TEXT NOT NULL,
  generated_at TEXT NOT NULL,
  PRIMARY KEY (project, path)
);

CREATE INDEX IF NOT EXISTS idx_entities_project_type ON entities(project, entity_type);
CREATE INDEX IF NOT EXISTS idx_entities_search ON entities USING gin(search_vector);
CREATE INDEX IF NOT EXISTS idx_obs_entity_id ON observations(entity_id);
CREATE INDEX IF NOT EXISTS idx_rel_project_from ON relations(project, from_entity_id);
CREATE INDEX IF NOT EXISTS idx_rel_project_to ON relations(project, to_entity_id);
CREATE INDEX IF NOT EXISTS idx_items_project_created ON memory_items(project, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_items_project_kind ON memory_items(project, kind);
CREATE INDEX IF NOT EXISTS idx_items_search ON memory_items USING gin(search_vector);
CREATE INDEX IF NOT EXISTS idx_episodes_project_created ON episodes(project, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_episodes_project_session ON episodes(project, session);
CREATE INDEX IF NOT EXISTS idx_episodes_search ON episodes USING gin(search_vector);
CREATE INDEX IF NOT EXISTS idx_memories_project_status ON semantic_memories(project, status);
CREATE INDEX IF NOT EXISTS idx_memories_project_subject ON semantic_memories(project, subject);
CREATE INDEX IF NOT EXISTS idx_memories_project_kind ON semantic_memories(project, kind);
CREATE INDEX IF NOT EXISTS idx_memories_project_scope ON semantic_memories(project, scope);
CREATE INDEX IF NOT EXISTS idx_memories_search ON semantic_memories USING gin(search_vector);
CREATE INDEX IF NOT EXISTS idx_memory_lifecycle_status
  ON memory_lifecycle(status, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_memory_sources_episode ON memory_sources(episode_id);
CREATE INDEX IF NOT EXISTS idx_conflicts_project_status ON memory_conflicts(project, resolution_status);
CREATE INDEX IF NOT EXISTS idx_aliases_project_canonical ON entity_aliases(project, canonical_name);
CREATE INDEX IF NOT EXISTS idx_claim_versions_memory_recorded ON claim_versions(memory_id, recorded_at DESC);
CREATE INDEX IF NOT EXISTS idx_claim_versions_project_status ON claim_versions(project, status);
CREATE INDEX IF NOT EXISTS idx_claim_versions_project_valid ON claim_versions(project, valid_from, valid_to);
CREATE INDEX IF NOT EXISTS idx_claim_versions_project_recorded ON claim_versions(project, recorded_at, retracted_at);
CREATE INDEX IF NOT EXISTS idx_claim_versions_search ON claim_versions USING gin(search_vector);
CREATE INDEX IF NOT EXISTS idx_evidence_claim_version ON memory_evidence(claim_version_id);
CREATE INDEX IF NOT EXISTS idx_evidence_episode ON memory_evidence(episode_id);
CREATE INDEX IF NOT EXISTS idx_resolution_events_conflict ON conflict_resolution_events(conflict_id, created_at);

CREATE INDEX IF NOT EXISTS idx_memory_embeddings_project_provider
  ON memory_embeddings(project, provider);
CREATE INDEX IF NOT EXISTS idx_memory_embeddings_hnsw
  ON memory_embeddings USING hnsw (embedding vector_cosine_ops)
  WITH (m = 16, ef_construction = 64);
CREATE INDEX IF NOT EXISTS idx_episode_embeddings_project_provider
  ON episode_embeddings(project, provider);
CREATE INDEX IF NOT EXISTS idx_episode_embeddings_hnsw
  ON episode_embeddings USING hnsw (embedding vector_cosine_ops)
  WITH (m = 16, ef_construction = 64);
CREATE INDEX IF NOT EXISTS idx_claim_version_embeddings_project_provider
  ON claim_version_embeddings(project, provider);
CREATE INDEX IF NOT EXISTS idx_claim_version_embeddings_hnsw
  ON claim_version_embeddings USING hnsw (embedding vector_cosine_ops)
  WITH (m = 16, ef_construction = 64);

CREATE OR REPLACE FUNCTION memorantado_relation_project_check()
RETURNS trigger
LANGUAGE plpgsql
AS $func$
DECLARE
  from_project TEXT;
  to_project TEXT;
BEGIN
  SELECT project INTO from_project FROM entities WHERE id = NEW.from_entity_id;
  SELECT project INTO to_project FROM entities WHERE id = NEW.to_entity_id;
  IF TG_OP = 'INSERT' THEN
    IF from_project IS NULL THEN
      RAISE EXCEPTION 'from_entity_id does not exist';
    END IF;
    IF to_project IS NULL THEN
      RAISE EXCEPTION 'to_entity_id does not exist';
    END IF;
  END IF;
  IF from_project IS DISTINCT FROM NEW.project THEN
    RAISE EXCEPTION 'from_entity_id project mismatch';
  END IF;
  IF to_project IS DISTINCT FROM NEW.project THEN
    RAISE EXCEPTION 'to_entity_id project mismatch';
  END IF;
  RETURN NEW;
END;
$func$;

DROP TRIGGER IF EXISTS relations_bi_project_consistency ON relations;
CREATE TRIGGER relations_bi_project_consistency
BEFORE INSERT ON relations
FOR EACH ROW EXECUTE FUNCTION memorantado_relation_project_check();

DROP TRIGGER IF EXISTS relations_bu_project_consistency ON relations;
CREATE TRIGGER relations_bu_project_consistency
BEFORE UPDATE OF project, from_entity_id, to_entity_id ON relations
FOR EACH ROW EXECUTE FUNCTION memorantado_relation_project_check();
`;

export async function ensurePgSchema(pool: Pool): Promise<void> {
  await pool.query(PG_SCHEMA_SQL);
}
